### PR TITLE
Remove unbeforeunload event when close PM panel

### PR DESCRIPTION
**Pull request by wezmag**
When a user type something in TinyMCE Editor in PM panel, it will registered an unbeforeunload event. (autosave plugin)
If we didn't remove the event after the PM panel is closed, the browser will prompt user, when they try to leave the page.

### CODE REVIEW

**Comment by leen3o** [comment]
I'm not following what this actually does, because I have purposely added this line.

https://github.com/leen3o/mvcforum/blob/master/MVCForum.Website/Scripts/general.js#L563

Which prompts the user if the TinyMCE editor is not empty before closing the PM panel?

**Comment by wezmag** [comment]
1. Open PM Panel, and type something in the editor (if there is already something, then type more words)
2. Close the PM panel **without** sending the message.
3. Click any link or just leave the page, then you will see the prompt.
image 1

**Comment by leen3o** [comment]
Ahhh I'm with you. I hadn't seen that before, thanks.

**Comment by leen3o** [comment]
Have added this in, thanks again

**Comment by wezmag** [comment]
A downside of remove unbeforeunload event is when a user close PM panel and reopen it, the text in TinyMCE editor will gone. It is because the autosave plugin uses unbeforeunload event to save the content (in cookie maybe).
This will not affect the TinyMCE editor in other pages.

**Comment by leen3o** [comment]
I have the reminder I linked to above, which asks the user if they want to close the window. If they confirm then they should expect the text to be lost IMO.

**Pull request closed without merging**
