### PR TITLE
Migrate to NuGet automatic package restore

### PR DESCRIPTION
**Pull request by davidglenn**
Migrate from MSBuild-Integrated package restore to automatic package restore in NuGet 2.7+. 

Once merged, remove the `/packages` directory and then rebuild.

### CODE REVIEW

**Comment by leen3o** [comment]
Unfortunately this breaks the build. So can't accept it.

[00:00:00] Build started
[00:00:09] git clone -q git://github.com/leen3o/mvcforum.git C:\projects\mvcforum
[00:00:39] git fetch -q origin +refs/pull/7/merge:
[00:00:43] git checkout -qf FETCH_HEAD
[00:00:46] "C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe" "MVCForum.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
[00:00:53] Microsoft (R) Build Engine version 12.0.31101.0
[00:00:53] [Microsoft .NET Framework, version 4.0.30319.34209]
[00:00:53] Copyright (C) Microsoft Corporation. All rights reserved.
[00:00:53] 
[00:01:24] C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "HtmlAgilityPack". Check to make sure the assembly exists on disk. If this reference i
[00:01:24] s required by your code, you may get compilation errors. [C:\projects\mvcforum\MVCForum.Utilities\MVCForum.Utilities.csproj]
[00:01:24] C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ImageProcessor". Check to make sure the assembly exists on disk. If this reference is
[00:01:24]  required by your code, you may get compilation errors. [C:\projects\mvcforum\MVCForum.Utilities\MVCForum.Utilities.csproj]
[00:01:25] C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ImageProcessor.Web". Check to make sure the assembly exists on disk. If this referenc
[00:01:25] e is required by your code, you may get compilation errors. [C:\projects\mvcforum\MVCForum.Utilities\MVCForum.Utilities.csproj]
[00:01:27] StringUtils.cs(11,7): error CS0246: The type or namespace name 'HtmlAgilityPack' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\mvcforum\MVCForum.Utilities\MVCForum.Utilities.csproj]
[00:01:28] Command exited with code 1

**Comment by davidglenn** [comment]
AppVeyor requires an additional setting to invoke the NuGet automatic package restore. Under the build section of the settings tab for the project, in the 'Before build script' field, select 'CMD' and enter 

`nuget restore`

This will invoke NuGet package restore when the project is built. <http://www.appveyor.com/docs/nuget#restoring-nuget-packages-before-build>

I have confirmed this works on my fork

appveyor

**Comment by leen3o** [comment]
Awesome thanks - Will pull in. How did you update the app? Was it a manual change or a setting in Visual Studio?

**Comment by davidglenn** [comment]
Cool. I manually edited the project files.

**Pull request merged**
